version: '3.0'

services:
  greptimedb:
    image: greptime/greptimedb:latest
    container_name: greptimedb
    command: standalone start --http-addr=0.0.0.0:4000 --rpc-addr=0.0.0.0:4001 --mysql-addr=0.0.0.0:4002
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    networks:
      - greptimedb-datasource
  grafana:
    user: root
    container_name: 'greptime-greptimedb-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/greptime-greptimedb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/greptime-greptimedb-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.greptime-greptimedb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: greptime-greptimedb-datasource
    networks:
      - greptimedb-datasource


networks:
  greptimedb-datasource:
