#########################################################################################
#
# - start jarvis developing dependencies only
#   docker compose -f local/compose.yml up greptimedb postgres redis -d
#
# - start grafana and prometheus with node_exporter
#   docker compose -f local/compose.yml up node_exporter prometheus grafana -d
#
#########################################################################################
version: '3.1'

services:
  greptimedb:
    image: greptime/greptimedb:latest
    container_name: greptimedb_info8fcc
    command: standalone start --http-addr=0.0.0.0:4000 --rpc-addr=0.0.0.0:4001 --mysql-addr=0.0.0.0:4002
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    networks:
      - datasource-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_info8fcc
    ports:
      - 9090:9090
    networks:
      - datasource-network
    volumes:
      - ./prometheus-greptimedb.yml:/etc/prometheus/prometheus.yml:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_info8fcc
    # ports:
    #   - 9100:9100
    command:
      - '--path.rootfs=/'
    networks:
      - datasource-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_info8fcc
    ports:
      - 3000:3000
    environment:
     - GF_INSTALL_PLUGINS=https://github.com/GreptimeTeam/greptimedb-grafana-datasource/releases/download/v1.0.36/info8fcc-greptimedb-datasource.zip;info8fcc
    volumes:
      # - ./info8fcc-greptimedb-datasource:/var/lib/grafana/plugins/info8fcc-greptimedb-datasource
      # - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ../provisioning:/etc/grafana/provisioning
    networks:
      - datasource-network

networks:
  datasource-network:
