name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: yarn build
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      -
        name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: build
      - name: zip
        run: yarn zip
      - name: build artifacts
        run: make build-linux && make build-windows && make build-darwin
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            info8fcc-greptimedb-datasource.zip